version: "3.7"
services:
  backend_base: &backendbase
    build:
      context: ./backend
      args:
        EXTRA_PACKAGES: graphviz-dev
        ENVIRONMENT: ${ENVIRONMENT}

  worker:
    <<: *backendbase

  backend:
    <<: *backendbase
